#pragma once

#ifdef __linux__

#include <X11/X.h>
#include <X11/keysym.h>

namespace volt::core {
  using KeyValueType = KeySym;

  enum class Key {
    Backspace   = XK_BackSpace,
    Enter       = XK_Return,
    Tab         = XK_Tab,
    Pause       = XK_Pause,
    Capital     = XK_Caps_Lock,
    Escape      = XK_Escape,
    Modechange  = XK_Mode_switch,
    Space       = XK_space,
    Pageup      = XK_Prior,
    Pagedown    = XK_Next,
    End         = XK_End,
    Home        = XK_Home,
    Left        = XK_Left,
    Up          = XK_Up,
    Right       = XK_Right,
    Down        = XK_Down,
    Select      = XK_Select,
    Print       = XK_Print,
    Execute     = XK_Execute,
    Insert      = XK_Insert,
    Delete      = XK_Delete,
    Help        = XK_Help,
    Num0        = XK_0,
    Num1        = XK_1,
    Num2        = XK_2,
    Num3        = XK_3,
    Num4        = XK_4,
    Num5        = XK_5,
    Num6        = XK_6,
    Num7        = XK_7,
    Num8        = XK_8,
    Num9        = XK_9,
    A           = XK_a,
    B           = XK_b,
    C           = XK_c,
    D           = XK_d,
    E           = XK_e,
    F           = XK_f,
    G           = XK_g,
    H           = XK_h,
    I           = XK_i,
    J           = XK_j,
    K           = XK_k,
    L           = XK_l,
    M           = XK_m,
    N           = XK_n,
    O           = XK_o,
    P           = XK_p,
    Q           = XK_q,
    R           = XK_r,
    S           = XK_s,
    T           = XK_t,
    U           = XK_u,
    V           = XK_v,
    W           = XK_w,
    X           = XK_x,
    Y           = XK_y,
    Z           = XK_z,
    LSuper      = XK_Meta_L,
    RSuper      = XK_Meta_R,
    Numpad0     = XK_KP_0,
    Numpad1     = XK_KP_1,
    Numpad2     = XK_KP_2,
    Numpad3     = XK_KP_3,
    Numpad4     = XK_KP_4,
    Numpad5     = XK_KP_5,
    Numpad6     = XK_KP_6,
    Numpad7     = XK_KP_7,
    Numpad8     = XK_KP_8,
    Numpad9     = XK_KP_9,
    Multiply    = XK_multiply,
    Add         = XK_KP_Add,
    Separator   = XK_KP_Separator,
    Subtract    = XK_KP_Subtract,
    Decimal     = XK_KP_Decimal,
    Divide      = XK_KP_Divide,
    F1          = XK_F1,
    F2          = XK_F2,
    F3          = XK_F3,
    F4          = XK_F4,
    F5          = XK_F5,
    F6          = XK_F6,
    F7          = XK_F7,
    F8          = XK_F8,
    F9          = XK_F9,
    F10         = XK_F10,
    F11         = XK_F11,
    F12         = XK_F12,
    F13         = XK_F13,
    F14         = XK_F14,
    F15         = XK_F15,
    F16         = XK_F16,
    F17         = XK_F17,
    F18         = XK_F18,
    F19         = XK_F19,
    F20         = XK_F20,
    F21         = XK_F21,
    F22         = XK_F22,
    F23         = XK_F23,
    F24         = XK_F24,
    Numlock     = XK_Num_Lock,
    Scroll      = XK_Scroll_Lock,
    NumpadEqual = XK_KP_Equal,
    LShift      = XK_Shift_L,
    RShift      = XK_Shift_R,
    LControl    = XK_Control_L,
    RControl    = XK_Control_R,
    LAlt        = XK_Alt_L,
    RAlt        = XK_Alt_R,
    Semicolon   = XK_semicolon,
    Equal       = XK_plus,
    Comma       = XK_comma,
    Minus       = XK_minus,
    Period      = XK_period,
    Slash       = XK_slash,
    Grave       = XK_grave
  };
}

#endif  // __linux__
