function (volt_set_c_compiler_options)
  set(CMAKE_C_STANDARD 17 CACHE STRING "C standard" FORCE)
  set(CMAKE_C_STANDARD_REQUIRED ON CACHE STRING "C standard required" FORCE)
  message(STATUS "Configured C standard: ${CMAKE_C_STANDARD}")
  set(CMAKE_C_EXTENSIONS ON CACHE STRING "C extensions" FORCE)
  message(STATUS "Configured C extensions: ${CMAKE_C_EXTENSIONS}")
  set(CMAKE_C_FLAGS_DEBUG "-fsanitize=address,undefined -g -Og" CACHE STRING "C flags (Debug)" FORCE)
  set(CMAKE_C_FLAGS_RELEASE "-DNDEBUG -pipe -O3" CACHE STRING "C flags (Release)" FORCE)
  if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    message(STATUS "Configured C flags: ${CMAKE_C_FLAGS_DEBUG}")
  elseif (CMAKE_BUILD_TYPE STREQUAL "Release")
    message(STATUS "Configured C flags: ${CMAKE_C_FLAGS_RELEASE}")
  endif()
endfunction()
